/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package comp3111_lab1;

public class Library {
	
	public static void main(String args[])
	{
		System.out.println("Hi there");
	}
	
    public boolean someLibraryMethod() {
        return true;
    }
}
